# Generated by Django 5.1.1 on 2024-09-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
