# Generated by Django 5.1.1 on 2024-09-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_artista_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('tipo_contacto', models.IntegerField(choices=[(0, 'sugerencia'), (1, 'reclamos'), (2, 'consultas')])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
